In [40]:
import numpy as np
import scipy as sp
import sympy as smp
import matplotlib.pyplot as plt
from scipy.misc import derivative

In [41]:
t0, t1, t2, t3 = smp.symbols('t0 t1 t2 t3', real=True)
t = [t0,t1,t2,t3]
print(t)

[t0, t1, t2, t3]


In [42]:
g = np.zeros((4,4), dtype = type(smp.sin(t0)))
print(met)
g[0][0] = 1
g[1][1] = smp.sin(t0)
g[2][2] = 1
g[3][3] = smp.sin(t2)
print(met)

[[1 0 0 0]
 [0 sin(t0) 0 0]
 [0 0 1 0]
 [0 0 0 sin(t2)]]
[[1 0 0 0]
 [0 sin(t0) 0 0]
 [0 0 1 0]
 [0 0 0 sin(t2)]]


In [43]:
g_inv = np.zeros((4,4), dtype = type(smp.sin(t0)))
g_inv[0][0] = 1
g_inv[1][1] = 1/smp.sin(t0)
g_inv[2][2] = 1
g_inv[3][3] = 1/smp.sin(t2)
print(met_inv)

[[1 0 0 0]
 [0 1/sin(t0) 0 0]
 [0 0 1 0]
 [0 0 0 1/sin(t2)]]


In [44]:
def calc_chrst():
    chrst = np.zeros((4,4,4), dtype = type(smp.sin(t0)))
    for k in range(4):
        for i in range(4): 
            for j in range(4):
                for m in range(4):
                    chrst[k][i][j] += (1/2)*g_inv[k][m]*(smp.diff(g[m][i],t[j]) + smp.diff(g[m][j],t[i]) - smp.diff(g[i][j],t[m]))
    return chrst

print(calc_chrst())
                    
    

[[[0 0 0 0]
  [0 -0.5*cos(t0) 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0.5*cos(t0)/sin(t0) 0 0]
  [0.5*cos(t0)/sin(t0) 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 -0.5*cos(t2)]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0.5*cos(t2)/sin(t2)]
  [0 0 0.5*cos(t2)/sin(t2) 0]]]


In [63]:
x, mu, s = smp.symbols('x mu s', real=True)
pdf = 1/(s*smp.sqrt(2*np.pi))*smp.exp(-1/2*((x-mu)/s)**2)
pdf_times_x = pdf * x
pdf_times_x

0.398942280401433*x*exp(-0.5*(-mu + x)**2/s**2)/s

In [58]:
# Ensuring integrating normal distribution over real numbers is 1
smp.integrate(pdf, (x,-smp.oo,smp.oo))

Piecewise((0.564189583547756*sqrt(pi), Abs(arg(s)) <= pi/4), (Integral(0.398942280401433*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [65]:
# Calculating Expected value of normal distribution
smp.integrate(pdf_times_x, (x,-smp.oo,smp.oo))

Piecewise((0.564189583547756*sqrt(pi)*mu, (Abs(arg(s)) <= pi/4) & (Abs(arg(s)) < pi/4)), (Integral(0.398942280401433*x*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [79]:
x, y, mu1, s1, mu2, s2 = smp.symbols('x y mu1 s1 mu2 s2', real=True)
# bivariate normal distribution
bi_pdf = 1/(s1*s2*np.sqrt(2*np.pi))*smp.exp(-1/2*(((x-mu1)/s1)**2+((y-mu2)/s2)**2))
bi_pdf

0.398942280401433*exp(-0.5*(-mu2 + y)**2/s2**2 - 0.5*(-mu1 + x)**2/s1**2)/(s1*s2)

In [80]:
# Calculating Expected value of bivariatte normal distribution
smp.integrate(bi_pdf, (x,-smp.oo,smp.oo), (y, -smp.oo, smp.oo))

RecursionError: maximum recursion depth exceeded in comparison